import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

/**
 * Physical Tailwind utilities that silently produce a correct-looking LTR
 * layout and a broken RTL one — the guaranteed offenders from the plan's RTL
 * risk list.
 *
 * The four ambiguous prefixes need a lookahead, because this project's own
 * `--color-line` token produces `border-line`, which starts with `border-l`.
 * A rule that cries wolf on the most-used class in the codebase gets disabled
 * within a day, which is worse than not having it.
 */
const PHYSICAL_UTILITIES = String.raw`(^|\s)(space-x-|divide-x-|ml-|mr-|pl-|pr-|left-|right-|text-left|text-right|border-l(?=[-\s]|$)|border-r(?=[-\s]|$)|rounded-l(?=[-\s]|$)|rounded-r(?=[-\s]|$))`;

const message =
  'Physical direction utility. Use the logical equivalent so RTL works: ' +
  'ms-/me-, ps-/pe-, start-/end-, text-start/text-end, border-s/border-e, ' +
  'rounded-s/rounded-e, gap-x-, space-y-, divide-y-.';

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is generated by Next on every build and is not ours to fix.
    ignores: ['.next/**', 'node_modules/**', 'drizzle/**', 'next-env.d.ts'],
  },
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      'no-restricted-syntax': [
        'error',
        // Class strings written directly on an element. Direct child only: a
        // `className={cn(...)}` literal is already covered by the joiner
        // selector below, and matching both reports the same string twice.
        {
          selector: `JSXAttribute[name.name='className'] > Literal[value=/${PHYSICAL_UTILITIES}/]`,
          message,
        },
        // Class strings passed through the joiners — most of this codebase's
        // conditional classes live here, and the attribute selector alone
        // misses every one of them.
        {
          selector: `CallExpression[callee.name=/^(cn|chipClass|buttonClass)$/] Literal[value=/${PHYSICAL_UTILITIES}/]`,
          message,
        },
      ],
    },
  },
  {
    // Test files assert on wall-clock strings and fixture shapes; the class
    // rule has nothing to say about them.
    files: ['**/*.test.ts'],
    rules: { 'no-restricted-syntax': 'off' },
  },
];

export default eslintConfig;
